Repository vimeo/iris, pull requests merged in 2021-06, with the labels that each got.

#23 Select: fix issue when passing values other than 'true' to 'disabled'
  src/components/inputs/Select/Select.minors.tsx
Labels: 🐛 bug

#26 Tip: force wrapping regardless of external CSS
  src/components/info/Annotation/Annotation.tsx
  src/components/info/Tip/Tip.style.ts
Labels: 🐛 bug

#24 icons: add PinAlt
  src/icons/ui/Pin.tsx
Labels: 🆕 enhancement

#19 Tip: support 'active' prop
  src/components/info/Tip/Tip.examples.story.tsx
  src/components/info/Tip/Tip.props.story.tsx
  src/components/info/Tip/Tip.tsx
  src/components/info/Tip/Tip.types.ts
Labels: 🆕 enhancement

#20 Button: story updates
  src/components/buttons/Button/Button.index.story.tsx
  src/components/buttons/Button/Button.props.story.tsx
  src/components/buttons/Button/examples/Growth.story.tsx
Labels: 📚 documentation

#25 color: add purple hue palette
  src/color/colorUtils.ts
  src/color/colors-brand.story.tsx
  src/color/colors-system.story.tsx
  src/color/colors.story.tsx
  src/color/colors.ts
  src/color/index.ts
  src/color/storyComponents.tsx
Labels: 🆕 enhancement

#18 typography: tokenize components
  src/components/info/Notice/Notice.style.ts
  src/components/inputs/Wrapper/Wrapper.tsx
  src/tokens/core.ts
  src/tokens/typography/index.ts
  src/tokens/typography/size/size.story.tsx
  src/tokens/typography/size/size.tsx
  src/tokens/typography/typography.story.tsx
  src/tokens/util/readToken.ts
  src/typography/BigStat/BigStat.props.story.tsx
  src/typography/BigStat/BigStat.story.tsx
  src/typography/Header/Header.props.story.tsx
  src/typography/Header/Header.story.tsx
  src/typography/Header/Header.style.ts
  src/typography/Header/Header.tsx
  src/typography/Link/Link.props.story.tsx
  src/typography/Link/examples/Custom.story.tsx
  src/typography/Paragraph/Paragraph.props.story.tsx
  src/typography/Paragraph/Paragraph.story.tsx
  src/typography/Paragraph/Paragraph.style.ts
  src/typography/Paragraph/Paragraph.tsx
  src/typography/Text/EditableText.tsx
  src/typography/Text/Text.examples.story.tsx
  src/typography/Text/Text.props.story.tsx
  src/typography/Text/Text.style.ts
  src/typography/Text/Text.tsx
  src/typography/Text/Text.types.ts
  src/typography/index.ts
  src/utils/css.ts
Labels: 🆕 enhancement
